-- Template Performance Data System Migration
-- Adds tables for storing historical backtest results, signals, and schedule configuration

-- Table 1: Template Performance Runs
-- Stores historical backtest runs for strategy templates
CREATE TABLE IF NOT EXISTS template_performance_runs (
    id VARCHAR(36) PRIMARY KEY,
    template_id VARCHAR(36) NOT NULL REFERENCES strategy_templates(id) ON DELETE CASCADE,

    -- Run metadata
    run_date TIMESTAMP WITH TIME ZONE NOT NULL,
    exchange VARCHAR(50) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    interval VARCHAR(20) NOT NULL,
    start_ms BIGINT,
    end_ms BIGINT,

    -- Metrics (JSONB matching BacktestRun.metrics structure)
    metrics JSONB,

    status VARCHAR(20) DEFAULT 'succeeded',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance runs
CREATE INDEX idx_perf_run_template ON template_performance_runs(template_id);
CREATE INDEX idx_perf_run_date ON template_performance_runs(run_date DESC);

-- Table 2: Template Signals
-- Stores historical signals generated by templates
CREATE TABLE IF NOT EXISTS template_signals (
    id VARCHAR(36) PRIMARY KEY,
    template_id VARCHAR(36) NOT NULL REFERENCES strategy_templates(id) ON DELETE CASCADE,

    -- Signal data
    symbol VARCHAR(50) NOT NULL,
    side VARCHAR(10) NOT NULL,
    price FLOAT NOT NULL,
    confidence FLOAT DEFAULT 0.0,
    status VARCHAR(20) DEFAULT 'executed',

    -- Outcome tracking
    entry_price FLOAT,
    exit_price FLOAT,
    pnl FLOAT,
    hold_duration_hours FLOAT,

    -- Metadata
    reason TEXT,
    indicators JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    executed_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT chk_signal_side CHECK (side IN ('buy', 'sell')),
    CONSTRAINT chk_signal_status CHECK (status IN ('pending', 'executed', 'cancelled', 'expired'))
);

-- Indexes for signals
CREATE INDEX idx_template_sig_template ON template_signals(template_id);
CREATE INDEX idx_template_sig_created ON template_signals(created_at DESC);

-- Table 3: Template Performance Schedule
-- Configuration for periodic performance updates
CREATE TABLE IF NOT EXISTS template_performance_schedule (
    id VARCHAR(36) PRIMARY KEY,
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    cron_expression VARCHAR(100) DEFAULT '0 2 * * *' NOT NULL,

    -- Generation config
    templates_per_batch INTEGER DEFAULT 5,
    backtest_days_history INTEGER DEFAULT 90,
    signals_per_day INTEGER DEFAULT 3,

    -- Data quality
    max_signals_per_template INTEGER DEFAULT 100,

    -- Tracking
    last_run_at TIMESTAMP WITH TIME ZONE,
    next_run_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default schedule
INSERT INTO template_performance_schedule (
    id,
    enabled,
    cron_expression,
    templates_per_batch,
    backtest_days_history,
    signals_per_day,
    max_signals_per_template
)
SELECT
    '00000000-0000-0000-0000-000000000001',
    TRUE,
    '0 2 * * *',
    5,
    90,
    3,
    100
WHERE NOT EXISTS (
    SELECT 1 FROM template_performance_schedule WHERE id = '00000000-0000-0000-0000-000000000001'
);

-- Add comments for documentation
COMMENT ON TABLE template_performance_runs IS 'Historical backtest runs for strategy templates';
COMMENT ON COLUMN template_performance_runs.metrics IS 'Performance metrics: total_return, sharpe_ratio, max_drawdown, win_rate, equity_curve, etc.';

COMMENT ON TABLE template_signals IS 'Historical signals generated by templates with outcomes';
COMMENT ON COLUMN template_signals.pnl IS 'Profit/loss percentage for executed signals';

COMMENT ON TABLE template_performance_schedule IS 'Schedule configuration for automatic template performance updates';
COMMENT ON COLUMN template_performance_schedule.cron_expression IS 'Cron expression for update schedule (default: daily at 2 AM UTC)';
